version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "root"
    ports:
      - "15432:5432"
    volumes:
      - C:\Users\Oséias\Documents\Docker-Compose\PostgreSQL:/var/lib/postgresql/data
    networks:
      - postgres-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge